In [775]:
import numpy as np
import PIL
from PIL import Image
import random
import cv2

In [776]:
im = Image.open('Im001_1.tif')

In [777]:
A = np.squeeze(im, axis=None)
print(np.shape(A))

(257, 257, 3)


In [778]:
E1 = random.choice(A)
F1 = random.choice(E1)
F1

array([151, 141, 132], dtype=uint8)

In [779]:
E2 = random.choice(A)
F2 = random.choice(E2)
F2

array([164, 166, 161], dtype=uint8)

In [780]:
E3 = random.choice(A)
F3 = random.choice(E3)
F3

array([143, 127, 127], dtype=uint8)

In [781]:
Gray1 = F1[0]*0.299 + F1[1]*0.587 + F1[2]*0.114
Gray1

142.964

In [782]:
Gray2 = F2[0]*0.299 + F2[1]*0.587 + F2[2]*0.114
Gray2

164.832

In [783]:
Gray3 = F3[0]*0.299 + F3[1]*0.587 + F3[2]*0.114
Gray3

131.784

In [784]:
U = [round(Gray1, 2), round(Gray2, 2), round(Gray3, 2)]
U

[142.96, 164.83, 131.78]

In [785]:
def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

In [786]:
find_nearest(U, jGray)

164.83

In [787]:
count = 0
B = []
for i in A:
    for j in i:
        jGray = j[0]*0.299 + j[1]*0.587 + j[2]*0.114
        o = find_nearest(U, jGray)
        if o == round(Gray1, 2):
            B.append([F1[0],F1[1],F1[2]])
            print('f1')
            count = count + 1
        elif o == round(Gray2, 2):
            B.append([F2[0],F2[1],F2[2]])
            print('f2')
            count = count + 1
        elif o == round(Gray3, 2):
            B.append([F3[0],F3[1],F3[2]])
            print('f3')
            count = count + 1

f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f2
f2
f2
f2
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f2
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f

f1
f1
f1
f1
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f2
f2
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f3
f3
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f1
f2
f1
f1
f

f2
f2
f2
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f3
f3
f3
f1
f3
f3
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f2
f2
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f3
f3
f3
f1
f1
f1
f1
f2
f

f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f

f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f

f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f1
f3
f3
f3
f3
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f1
f3
f3
f3
f3
f3
f2
f2
f2
f2
f2
f

f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f

f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f3
f3
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f

f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f

f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f

f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f

f3
f3
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f

f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f

f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f2
f2
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f

f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f3
f3
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f2
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f1
f1
f1
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f

f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f3
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f1
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f2
f

In [788]:
A

array([[[139, 120, 122],
        [141, 121, 123],
        [143, 123, 125],
        ...,
        [150, 131, 137],
        [147, 131, 132],
        [144, 128, 129]],

       [[142, 124, 124],
        [141, 121, 122],
        [140, 120, 121],
        ...,
        [147, 131, 134],
        [145, 131, 131],
        [142, 128, 127]],

       [[131, 121, 120],
        [132, 122, 121],
        [134, 122, 122],
        ...,
        [149, 130, 134],
        [149, 130, 132],
        [149, 129, 131]],

       ...,

       [[161, 165, 164],
        [162, 166, 165],
        [158, 162, 163],
        ...,
        [161, 167, 157],
        [160, 165, 158],
        [160, 165, 159]],

       [[157, 161, 160],
        [162, 166, 165],
        [160, 164, 165],
        ...,
        [163, 168, 161],
        [162, 167, 160],
        [161, 166, 162]],

       [[155, 160, 156],
        [164, 168, 167],
        [162, 166, 165],
        ...,
        [162, 167, 161],
        [161, 166, 160],
        [161, 165, 164]]

In [789]:
len(B)

66049

In [790]:
C = np.array(B)
C

array([[143, 127, 127],
       [143, 127, 127],
       [143, 127, 127],
       ...,
       [164, 166, 161],
       [164, 166, 161],
       [164, 166, 161]], dtype=uint8)

In [791]:
D = np.reshape(C,np.shape(A))
D

array([[[143, 127, 127],
        [143, 127, 127],
        [143, 127, 127],
        ...,
        [143, 127, 127],
        [143, 127, 127],
        [143, 127, 127]],

       [[143, 127, 127],
        [143, 127, 127],
        [143, 127, 127],
        ...,
        [143, 127, 127],
        [143, 127, 127],
        [143, 127, 127]],

       [[143, 127, 127],
        [143, 127, 127],
        [143, 127, 127],
        ...,
        [143, 127, 127],
        [143, 127, 127],
        [143, 127, 127]],

       ...,

       [[164, 166, 161],
        [164, 166, 161],
        [164, 166, 161],
        ...,
        [164, 166, 161],
        [164, 166, 161],
        [164, 166, 161]],

       [[164, 166, 161],
        [164, 166, 161],
        [164, 166, 161],
        ...,
        [164, 166, 161],
        [164, 166, 161],
        [164, 166, 161]],

       [[164, 166, 161],
        [164, 166, 161],
        [164, 166, 161],
        ...,
        [164, 166, 161],
        [164, 166, 161],
        [164, 166, 161]]

In [792]:
img1 = Image.fromarray(D, 'RGB')
img1.show()
img1.save('my.tif')

In [793]:
img_a = cv2.imread('Im001_1.tif')
img_b = cv2.imread('my.tif')
PSNR_score = cv2.PSNR(img_a, img_b)
PSNR_score

18.225597877837753